server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_ROOT_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    health:
      show-details: always
      probes:
        enabled: true
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET}
  expiry:
    access: 3600000
    refresh: 604800000

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}