apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  MYSQL_ROOT_USERNAME: root
  MYSQL_ROOT_PASSWORD: root
  JWT_SECRET: 8ozzId5fCBrhVYvUu0jbSvVF3c69XsHV0LNJAMwpLUw=
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: Admin@123