apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
stringData:
  JWT_SECRET: 8ozzId5fCBrhVYvUu0jbSvVF3c69XsHV0LNJAMwpLUw=
  MONGODB_URI: mongodb://root:root@mongo.infra:27017/ecommerce?authSource=admin
  RABBITMQ_HOST: rabbitmq.infra
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: user
  RABBITMQ_PASSWORD: User@123