name: Auth Service CI
run-name: New changes found in repository ${{ github.repository }}
on:
  push:
    branches:
      - main
    paths:
      - 'auth-service/k8s/**'
      - 'auth-service/src/**'
      - 'auth-service/Dockerfile'
      - 'auth-service/pom.xml'
concurrency:
  group: auth-service-ci
  cancel-in-progress: true
env:
  IMAGE_NAME: gauravd70/ecommerce-auth
  IMAGE_TAG: ${{ github.sha }}
jobs:
  ci:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: auth-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate settings.xml
        uses: Gauravd70/CI-Actions/maven-settings@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
      - name: Build
        run: mvn clean package

      - name: Docker Build
        uses: Gauravd70/CI-Actions/docker-build@v8
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ env.IMAGE_TAG }}
          context: auth-service

      - name: DockerHub Login
        uses: Gauravd70/CI-Actions/docker-login@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Docker Push
        uses: Gauravd70/CI-Actions/docker-push@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ env.IMAGE_TAG }}

      - name: Docker Push
        uses: Gauravd70/CI-Actions/docker-push@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: 'latest'